instance_name = "app_server_instance"
machine_type = "e2-medium"
zone = "us-central1-a"
boot_disk_image = "ubuntu-os-cloud/ubuntu-1804-lts"
startup_script =""
network_name = "vpc-network"
subnet_name = "test-subnetwork"
subnet_ip_cidr_range = "10.2.0.0/16"